export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_END = 'LOGIN_USER_END';
export const ERROR_USER_LOGIN = 'ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_END = 'SIGNUP_USER_END';
export const ERROR_USER_SIGNUP = 'ERROR_USER_SIGNUP';
export const SIGNNUP_RESET = 'SIGNNUP_RESET';
